server.port=8083

spring.application.name=order-service

# ===============================
# JWT
# ===============================
jwt.secret=CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te

# ===============================
# MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Product Service
# ===============================
product-service.base-url=http://localhost:8082

# Trong giai ?o?n test ??c l?p:
# false = Order v?n ch?y ???c khi Product Service ch?a hoàn thi?n.
#
# Sau khi TV2 hoàn thành Product Service,
# có th? ??i thành true ?? Order ki?m tra Product qua REST API.
product-service.validation-enabled=false